spring:
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.112.1:3306/permission
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 打印sql语句
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.by.model
